# Function to consistently read the configuration files generated by
# P2_Indices.R and P4_Region_Average.R
# Scripts reading configuration files should first 'source' this file
# and pass either "P2" or "P4" to get the appropriate files

read_configuration <- function(ctype) {

# Check that appropriate configuration file exists
# and set up list of output values

  ctype <- match.arg(ctype,c("P2","P4"))
  if (ctype == "P2") {
    namex <- file.path("A2_Indices","P2_Configuration.txt")
  } else {
    namex <- file.path("A4_Region_Average","P4_Configuration.txt")
  }
  if (!file.exists(namex))
    {stop(ctype," configuration file has been found.",
	  "\nCheck that script has been successfully completed.")}

# Read in configuration file and extract values to list
# Where required, convert from character to integer or numeric

  clines <- readLines(namex)
  xx <- strsplit(clines," = ")
  olist <- lapply(xx,"[",2)
  olist[[2]] <- as.integer(olist[[2]])
  olist[[3]] <- as.integer(olist[[3]])
  olist[[4]] <- as.integer(olist[[4]])
  if (ctype == "P2") {
    olist[[5]] <- as.integer(olist[[5]])
    olist[[6]] <- as.integer(olist[[6]])
    names(olist) <- c("date","nstn","nyb","nye","QCT","QCPr")
  } else {
    olist[[7]] <- as.numeric(olist[[7]])
	names(olist) <- c("date","nstn","nyb","nye","tcode","tname","res","uncode2")
  }

# Return the processed list

  olist
}
